### ISSUE TITLE
plugin reports differently when same project is scanned within intellij-ue as opposed to intellij-ce

### ISSUE THREAD

**Issue by jwtodd** [Checkmarx/ast-jetbrains-plugin#116]
[see: [checker:forum](https://source.checkmarx.com/t/jetbrains-intellij-checkmarx-plugin/597) ]

hi -

the [intellij package checker plugin](https://plugins.jetbrains.com/plugin/18337-package-checker) is quite nice. it works really well in intellij-ue (ultimate edition) but we are not seeing it report the same vulnerabilities in the same java/gradle project when running in intellij-ce (community edition).

i’ve looked through the [checkmarx intellij plugin documentation](https://checkmarx.com/resource/documents/en/34965-111887-checkmarx-dependency-checker-plugin-for-jetbrains-intllij-idea.html) and have yet to find an answer. the docs are quite nice btw.

to summarize, should the checkmarx package-checker intellij plugin work the same in intellij-ce as it does in intellij-ue?

latests: intellij-ue, intellij-ce, package-checker plugin
toolchain: jdk:17, gradle:7.5, intellij

thoughts?

thx,

- james

**Comment by pedrompflopes** [comment]
@jwtodd Thanks for raising this, but the plugin we have in this repo is this one:

https://plugins.jetbrains.com/plugin/17672-checkmarx-ast

Thanks.

**Comment by jwtodd** [comment]
@pedrompflopes yeah that's the one we installed. no where other then here could i find a means to register the issue.

as such, what do you suggest as the solution?
