### ISSUE TITLE
[BUG] only 20 first branches are listed per project

### ISSUE THREAD

**Issue by DBarthe** [Checkmarx/ast-jetbrains-plugin#183]
### Describe the bug

The branches listed are limited to 20 results

### Expected behavior

The branch selector should allow to select any branch in the project.

### Actual behavior

The selector allows to select only one of the 20 first branches.

### Steps to reproduce

1. select a project with more than 20 branches.
2. open the branches selector
3. see there is only 20 branches listed

### Environment
- JETBRAINS PLUGIN version 2.0.8
- Linux

### Additional comments

I think i've identified the cause of this error.

By default the `cx` CLI returns only the 20 first branches with `cx project branches --project-id xxxxx`.
You should add `--filter limit=1000` to list the 1000 first branches instead.

This plugin code seems to somehow wrap the CLI.

**Comment by DBarthe** [comment]
Not related, it would be nice if it could automatically select the current opened projects and branches

**Comment by diogopcx** [comment]
Hi @DBarthe!
This is fixed in version 2.0.10.
Thank you for reporting the issue.
